# Sequence Matching for Annotation between K-12 and REL606

To understand Regulon and other papers, a convertion between genes are necessary.

In [183]:
# trail #1
# http://biopython.org/DIST/docs/api/Bio.pairwise2-module.html
from Bio import pairwise2
alignments = pairwise2.align.globalxx("ACCGT", "ACG")

from Bio.pairwise2 import format_alignment
print(format_alignment(*alignments[0]))

ACCGT
| ||
A-CG-
  Score=3

# 1. Load 
### 1.1 Load packages

In [184]:
import pandas as pd
from Bio import pairwise2
import rglonDB_parse as rp
from Bio import SeqIO
import numpy as np
import time

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

### 1.2 Load regulon files

In [185]:
reg_gen_file = "HelpFiles/gene.txt"

In [186]:
# read regulon file
reg_gene = rp.txt_parse(reg_gen_file)
reg_gene.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11
0,ECK120000001,alr,4265782.0,4266861.0,forward,ATGCAAGCGGCAACTGTTGTGATTAACCGCCGCGCTCTGCGACACA...,55.93,NaN,NaN,NaN,ECK12,NaN
1,ECK120000002,modB,795862.0,796551.0,forward,ATGATACTGACCGATCCAGAATGGCAGGCAGTTTTATTAAGCCTGA...,54.06,NaN,NaN,NaN,ECK12,NaN
2,ECK120000003,cysZ,2531463.0,2532224.0,forward,ATGGTTTCATCATTCACATCTGCCCCACGCAGCGGTTTTTACTATT...,50.13,NaN,NaN,NaN,ECK12,NaN

In [187]:
# adding column names for the dataframe
col_names = ["uniqueID", "name", "pos_left", "pos_right", 
             "direct", "sequence", "GC_content", "CRI_score",
            "note", "internal_comment", "key_id_org", "type"]
reg_gene.columns = col_names
reg_gene.head(3)

,uniqueID,name,pos_left,pos_right,direct,sequence,GC_content,CRI_score,note,internal_comment,key_id_org,type
0,ECK120000001,alr,4265782.0,4266861.0,forward,ATGCAAGCGGCAACTGTTGTGATTAACCGCCGCGCTCTGCGACACA...,55.93,NaN,NaN,NaN,ECK12,NaN
1,ECK120000002,modB,795862.0,796551.0,forward,ATGATACTGACCGATCCAGAATGGCAGGCAGTTTTATTAAGCCTGA...,54.06,NaN,NaN,NaN,ECK12,NaN
2,ECK120000003,cysZ,2531463.0,2532224.0,forward,ATGGTTTCATCATTCACATCTGCCCCACGCAGCGGTTTTTACTATT...,50.13,NaN,NaN,NaN,ECK12,NaN

In [188]:
reg_gene.loc[20, "name"]

'aceE'

In [189]:
pd.isnull(reg_gene.loc[2682, "name"])

True

In [190]:
reg_gene[reg_gene.name.isna()]

,uniqueID,name,pos_left,pos_right,direct,sequence,GC_content,CRI_score,note,internal_comment,key_id_org,type
2682,ECK120002704,NaN,15869.0,16177.0,reverse,GTGCCGGAAAGGGAGCTCCGGCTTTTTTATTACCTGAATTGCCTAT...,52.10,NaN,NaN,NaN,ECK12,Phantom Gene
2875,ECK120002902,NaN,565972.0,566532.0,forward,GTGACATTTTCTTTCCTCTGTTATGCCATCACCCGCGCTCACCTGG...,52.58,NaN,NaN,NaN,ECK12,Phantom Gene
2915,ECK120002943,NaN,643407.0,643868.0,forward,ATGCTTCTGCCATGGTTATTCCCACAAACGAAACGGAATAATTTTG...,51.73,NaN,NaN,NaN,ECK12,Phantom Gene
3242,ECK120003273,NaN,1419168.0,1419344.0,forward,GTGCTTCTCCAACCATCGGCGCGCACCAGTTTCGGTTTTAAATGTT...,48.59,NaN,NaN,NaN,ECK12,Phantom Gene
3254,ECK120003285,NaN,1426055.0,1426288.0,forward,TTGCCACCGATACCGGAACCAGAAATAGACCCGGTGCTTAAGGAGT...,47.01,NaN,NaN,NaN,ECK12,Phantom Gene
3297,ECK120003329,NaN,1498432.0,1498635.0,reverse,GTGGCTGACAAGGTGTATCTGAAATACACACCATCAGATTACTCAT...,47.06,NaN,NaN,NaN,ECK12,Phantom Gene
3305,ECK120003337,NaN,1509250.0,1509447.0,reverse,TTGTTTCAGGATTGCTTTACGCAATGGTTCTTTAATCTCATCGCAG...,49.49,NaN,NaN,NaN,ECK12,Phantom Gene
3585,ECK120003620,NaN,1987444.0,1987782.0,forward,ATGCATTGCGCCGATGAAGGTTTTGAGAAACCGCTGCCTCATCTGT...,47.49,NaN,NaN,NaN,ECK12,Phantom Gene
3665,ECK120003706,NaN,2167735.0,2168001.0,reverse,ATGTGGAGAGTGAGAATATTTTTTGGTAAGCGTCAAATATGCGCGT...,47.94,NaN,NaN,NaN,ECK12,Phantom Gene
3879,ECK120003922,NaN,2736913.0,2737119.0,forward,TTGAGCTGCCGTTTTTTTATTCTGTCAGTTGTGAAACTGAAGCGAT...,36.23,NaN,NaN,NaN,ECK12,Phantom Gene
3911,ECK120003956,NaN,2785800.0,2785973.0,reverse,ATGGAGGCGGTGTCGGGTTTTATGTCGCGTGTAATCACGACCCAAG...,41.95,NaN,NaN,NaN,ECK12,Phantom Gene
4069,ECK120004120,NaN,3150722.0,3150967.0,forward,GTGAACGCCTTATCCGGCCTACAAACGCACGAAGATTCAACATGTT...,48.78,NaN,NaN,NaN,ECK12,Phantom Gene
4070,ECK120004121,NaN,3151977.0,3152132.0,reverse,GTGCTGGTGACTTTTTTACTGCGTAAACGCAAGGAAAAGAAAGCAA...,41.03,NaN,NaN,NaN,ECK12,Phantom Gene
4266,ECK120004318,NaN,4175213.0,4175368.0,reverse,ATGGAGACATGCGAGTTCATGCAACTAAAAAATTGCATAATTTGTT...,39.74,NaN,NaN,NaN,ECK12,Phantom Gene
4320,ECK120004373,NaN,4472513.0,4472845.0,forward,ATGTCGAACACACTGAACCATACATCCTCCCGGCAAATTGTCCGGC...,41.74,NaN,NaN,NaN,ECK12,Phantom Gene
4323,ECK120004376,NaN,4474227.0,4474391.0,forward,ATGCTGTCAGTGTTGCTGAAGTTACTGATTATCTTGGTATTAACCC...,47.88,NaN,NaN,NaN,ECK12,Phantom Gene
4398,ECK120004454,NaN,733370.0,733591.0,forward,GTGAAAGAAGCGGTCCAGATATATGGGGGAATCCGTTCTATCATCA...,45.50,NaN,NaN,NaN,ECK12,Phantom Gene
4571,ECK125135293,NaN,NaN,NaN,NaN,TGCCTTTGGTAGAGGAAAGTGCTAAGGAAGGCTAAATAATAATCAA...,36.60,NaN,Resequencing of multiple isolates of the MG165...,NaN,NaN,NaN
4572,ECK125135295,NaN,1670949.0,1671136.0,reverse,TGCGCATCAGTAATAAATGACACACAGCAAAATGAATCCGTTTATT...,45.21,NaN,NaN,NaN,ECK12,NaN
4574,ECK125135299,NaN,2278258.0,2278498.0,reverse,CGATATATGTTTATTTTATGTAAAATCAATTTATGTAAAAAGTCAC...,36.93,NaN,NaN,NaN,ECK12,NaN
4576,ECK125135303,NaN,3354064.0,3354169.0,forward,GCGCCTTGAAAAGAGGCCAAAGCCTGCCATTTTTAGCTCAATTCGG...,45.28,NaN,NaN,NaN,ECK12,NaN
4577,ECK125135305,NaN,3367613.0,3367770.0,reverse,GGTGAGCACTGAACAATTAAGAACAGCGTATTACATTTACTTTCCC...,40.51,NaN,NaN,NaN,ECK12,NaN
4578,ECK125135307,NaN,4001191.0,4001334.0,forward,CACGATCACTCTAAGAGGACATTCGCCTTGGACACACCCAGTAGAT...,50.00,NaN,NaN,NaN,ECK12,NaN
4579,ECK125135309,NaN,4058171.0,4058242.0,forward,CCATCGTGCAAAAGGGCTGCACCACGATGTGAATGTTGCACCAATA...,44.44,NaN,NaN,NaN,ECK12,NaN
4580,ECK125135311,NaN,4441225.0,4441330.0,reverse,ATACTAGCCACTGAAAATGCCGGTTCACTTTCTTCGAATCGGCTTT...,43.40,NaN,NaN,NaN,ECK12,NaN

In [191]:
reg_gene.shape

(4686, 12)

### 1.3 Load NCBI files
### 1.3.1 NCBI ann

In [192]:
# read ncbi annotation file
ncbi_gene_file = "HelpFiles/REL606_gbk_annotation.csv"
ncbi_ann = pd.read_csv(ncbi_gene_file, header=0, index_col=0)
ncbi_ann.head(3)

,locus_tag,name,location,old_locus_tag,product,note,start,end
0,ECB_RS00005,thrL,[189:255](+),ECB_00001,thr operon leader peptide,Derived by automated computational analysis us...,189,255
1,ECB_RS00010,thrA,[335:2798](+),ECB_00002,bifunctional aspartate kinase/homoserine dehyd...,Derived by automated computational analysis us...,335,2798
2,ECB_RS00015,thrB,[2799:3732](+),ECB_00003,homoserine kinase,Derived by automated computational analysis us...,2799,3732

In [193]:
ncbi_ann.shape

(4488, 8)

### 1.3.2 NCBI sequence

In [194]:
# I'll need the actual sequence for each ECB#
ncbi_seq_file = "HelpFiles/NCBI_rel606/NCBI_EcoliBREL606_Fall2019.fa"
gen_ids = []
seq_list = []
for record in SeqIO.parse(ncbi_seq_file, "fasta"):
    if "NC_012967" in record.id:
        seq = str(record.seq)
        des = record.description
        des = des.split()
        for words in des:
            if "locus_tag" in words:
                ecb = words[11:-1]
        gen_ids.append(ecb)
        seq_list.append(seq)
        #print(record, des, ecb, seq, "\n")

In [195]:
ncbi_seq = pd.DataFrame({"id": gen_ids, "sequence": seq_list})
ncbi_seq.head(3)

            id                                           sequence
0  ECB_RS00005  ATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCA...
1  ECB_RS00010  ATGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGCAAATGCAGAAC...
2  ECB_RS00015  ATGGTTAAAGTTTATGCCCCGGCTTCCAGTGCCAATATGAGCGTCG...

In [196]:
ncbi_seq.shape

(4488, 2)

### 1.3.3 Merge NCBI ann and sequence

In [197]:
ncbi_info = pd.merge(
    ncbi_ann, ncbi_seq,
    how = "left",
    left_on = 'locus_tag',
    right_on = "id"
)
ncbi_info.head(3)

,locus_tag,name,location,old_locus_tag,product,note,start,end,id,sequence
0,ECB_RS00005,thrL,[189:255](+),ECB_00001,thr operon leader peptide,Derived by automated computational analysis us...,189,255,ECB_RS00005,ATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCA...
1,ECB_RS00010,thrA,[335:2798](+),ECB_00002,bifunctional aspartate kinase/homoserine dehyd...,Derived by automated computational analysis us...,335,2798,ECB_RS00010,ATGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGCAAATGCAGAAC...
2,ECB_RS00015,thrB,[2799:3732](+),ECB_00003,homoserine kinase,Derived by automated computational analysis us...,2799,3732,ECB_RS00015,ATGGTTAAAGTTTATGCCCCGGCTTCCAGTGCCAATATGAGCGTCG...

In [198]:
ncbi_info.drop(["id"], axis=1, inplace=True)
ncbi_info.head(3)

,locus_tag,name,location,old_locus_tag,product,note,start,end,sequence
0,ECB_RS00005,thrL,[189:255](+),ECB_00001,thr operon leader peptide,Derived by automated computational analysis us...,189,255,ATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCA...
1,ECB_RS00010,thrA,[335:2798](+),ECB_00002,bifunctional aspartate kinase/homoserine dehyd...,Derived by automated computational analysis us...,335,2798,ATGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGCAAATGCAGAAC...
2,ECB_RS00015,thrB,[2799:3732](+),ECB_00003,homoserine kinase,Derived by automated computational analysis us...,2799,3732,ATGGTTAAAGTTTATGCCCCGGCTTCCAGTGCCAATATGAGCGTCG...

In [199]:
ncbi_info.name.isna().sum()

2151

In [200]:
ncbi_info.shape

(4488, 9)

In [201]:
ncbi_info.to_csv("HelpFiles/NCBI_EcoliBREL606_annseq.csv")

# 2. Sequence alignment
### 2.1 Matching by conventional names

In [202]:
ncbi_info.dtypes

locus_tag        object
name             object
location         object
old_locus_tag    object
product          object
note             object
start             int64
end               int64
sequence         object
dtype: object

In [203]:
reg_gene.dtypes

uniqueID             object
name                 object
pos_left            float64
pos_right           float64
direct               object
sequence             object
GC_content          float64
CRI_score           float64
note                 object
internal_comment    float64
key_id_org           object
type                 object
dtype: object

In [204]:
len(reg_gene), reg_gene.shape, ncbi_info.shape

(4686, (4686, 12), (4488, 9))

In [205]:
# if the name of regulon genes is in the ncbi name list, then math their id directly

i = 0
ncbi_names = ncbi_info.name.tolist()
reg_name_match_ids = []
ncbi_name_match_ids = []
while i<len(reg_gene):
    
    reg_name = reg_gene.loc[i, "name"]
    reg_id = reg_gene.loc[i, "uniqueID"]
    
    #print(reg_id, reg_name)
    
    if pd.isnull(reg_name)==False and (reg_name in ncbi_names):
        ncbi_id = ncbi_info.loc[ncbi_info.name==reg_name, "locus_tag"].values[0]
        #print(reg_id, ncbi_id)
        
        reg_name_match_ids.append(reg_id)
        ncbi_name_match_ids.append(ncbi_id)

    i = i+1

In [206]:
len(ncbi_name_match_ids), len(reg_name_match_ids)

(2173, 2173)

### 2.2 Matching by sequenc alignment

In [207]:
ncbi_left = ncbi_info[~ncbi_info.locus_tag.isin(ncbi_name_match_ids)]
ncbi_left.head(3)

,locus_tag,name,location,old_locus_tag,product,note,start,end,sequence
4,ECB_RS00030,NaN,[5231:5528](+),ECB_00005,DUF2502 domain-containing protein,Derived by automated computational analysis us...,5231,5528,ATGAAAAAGATGCAATCTATCGTACTCGCACTTTCCCTGGTTCTGG...
6,ECB_RS00040,NaN,[6526:7957](-),ECB_00007,sodium:alanine symporter family protein,Derived by automated computational analysis us...,7957,6526,ATGCCAGATTTTTTCTCCTTTATTAACAGCGTCCTTTGGGGATCGG...
7,ECB_RS00045,tal,[8235:9189](+),ECB_00008,transaldolase,Derived by automated computational analysis us...,8235,9189,ATGACGGACAAATTGACCTCCCTTCGTCAGTACACCACCGTAGTGG...

In [208]:
reg_left = reg_gene[~reg_gene.uniqueID.isin(reg_name_match_ids)]
reg_left.head(3)

,uniqueID,name,pos_left,pos_right,direct,sequence,GC_content,CRI_score,note,internal_comment,key_id_org,type
3,ECK120000004,dfp,3812731.0,3813951.0,forward,ATGAGCCTGGCCGGTAAAAAAATCGTTCTCGGCGTTAGCGGCGGTA...,53.64,NaN,NaN,NaN,ECK12,NaN
4,ECK120000005,dcuB,4347404.0,4348744.0,reverse,ATGTTATTTACTATCCAACTTATCATAATACTGATATGTCTGTTTT...,52.27,NaN,NaN,NaN,ECK12,NaN
5,ECK120000006,hisM,2424517.0,2425233.0,reverse,GTGATCGAAATCTTACATGAATACTGGAAACCGCTGCTGTGGACCG...,49.65,NaN,NaN,NaN,ECK12,NaN

In [209]:
ncbi_left.shape, reg_left.shape

((2315, 9), (2513, 12))

In [210]:
reg_left.sequence.str.len().describe()

count    2510.000000
mean      799.672112
std       650.505590
min        14.000000
25%       315.000000
50%       687.000000
75%      1107.000000
max      6063.000000
Name: sequence, dtype: float64

In [211]:
ncbi_id = ncbi_left.locus_tag.tolist()
regulon_id = reg_left.uniqueID.tolist()

nc_gene_len = []
re_gene_len = []
nc_id_match = []
align_score = []
align_len = []
align_similarity = []
i = 0
for rg_id in regulon_id:
    
    score_list = []
    length_list = []
    start = time.time()
    
    for nc_id in ncbi_id:
        
        reg_seq = reg_left.loc[reg_left.uniqueID==rg_id, "sequence"].values
        ncb_seq = ncbi_left.loc[ncbi_left.locus_tag==nc_id, "sequence"].values
        
        re_len = float(reg_left.loc[reg_left.uniqueID==rg_id, "sequence"].str.len())
        nc_len = float(ncbi_left.loc[ncbi_left.locus_tag==nc_id, "sequence"].str.len())
        
        if nc_len>1.25*re_len or nc_len<0.25*re_len:
            continue
        else:
        
            align = pairwise2.align.globalxx(reg_seq, ncb_seq,  
                                          penalize_extend_when_opening = True,
                                          one_alignment_only = True)
            score = float(align[0][2])
            length = float(align[0][4])

            score_list.append(score)
            length_list.append(length)
    
    if len(similarity_list)==0:
        continue
    else:
        similarity_list = np.asarray(score_list)/np.asanyarray(length_list)
        ind = np.argmax(similarity_list)    # select the index for the max similarities

        final_score = score_list[ind]
        final_len = length_list[ind]
        final_similarity = similarity_list[ind]
        final_nc_id = ncbi_id[ind]
        re_len = float(reg_left.loc[reg_left.uniqueID==rg_id, "sequence"].str.len())
        nc_len = float(ncbi_left.loc[ncbi_left.locus_tag==final_nc_id, "sequence"].str.len())

        nc_gene_len.append(nc_len)
        re_gene_len.append(re_len)
        nc_id_match.append(final_nc_id)
        align_score.append(final_score)
        align_len.append(final_len)
        align_similarity.append(final_similarity)

        end = time.time()

        print(rg_id, final_nc_id, final_similarity, re_len, end - start, i)  
        
    i = i+1

ECK120000004 ECB_RS12525 0.9902518277822908 1221.0 134.54414892196655 0
ECK120000005 ECB_RS14455 0.9911176905995559 1341.0 155.88393568992615 1
ECK120000006 ECB_RS25410 1.0 717.0 40.999874114990234 2
ECK120000008 ECB_RS02205 0.515993265993266 2049.0 281.8707537651062 3
ECK120000018 ECB_RS13910 0.9258517034068137 957.0 80.12785005569458 4
ECK120000024 ECB_RS07815 0.9966914805624483 1203.0 133.23858094215393 5
ECK120000027 ECB_RS05515 1.0 1002.0 88.32511401176453 6
ECK120000029 ECB_RS01305 0.9696509863429439 645.0 32.99906897544861 7
ECK120000030 ECB_RS25355 0.9699604743083003 1242.0 144.8663239479065 8
ECK120000036 ECB_RS14150 0.9502999143101971 1134.0 120.40314173698425 9
ECK120000041 ECB_RS25395 0.9980430528375733 1017.0 89.29976487159729 10
ECK120000045 ECB_RS03565 0.9923547400611621 1299.0 153.30749416351318 11
ECK120000046 ECB_RS01755 1.0 750.0 48.33774280548096 12
ECK120000047 ECB_RS25305 1.0 552.0 23.341511249542236 13
ECK120000052 ECB_RS09260 0.9791376912378303 1419.0 175.7486228942871 14
ECK120000053 ECB_RS25400 1.0 990.0 86.45569801330566 15
ECK120000054 ECB_RS06805 1.0 1515.0 192.09743523597717 16
ECK120000055 ECB_RS06485 1.0 987.0 86.30980086326599 17
ECK120000059 ECB_RS09230 0.9777942264988897 1332.0 157.70011687278748 18
ECK120000062 ECB_RS11170 1.0 1221.0 140.78137493133545 19
ECK120000065 ECB_RS11360 0.5015060240963856 1005.0 90.25917315483093 20
ECK120000079 ECB_RS01140 0.9854439592430859 678.0 36.89790940284729 21
ECK120000081 ECB_RS08785 0.8227040816326531 1425.0 175.20248103141785 22
ECK120000083 ECB_RS08315 0.9510556621880998 1011.0 89.964919090271 23
ECK120000085 ECB_RS12840 0.9004006868918145 1656.0 216.98942303657532 24
ECK120000086 ECB_RS13275 0.8902439024390244 1236.0 145.58378911018372 25
ECK120000088 ECB_RS02240 0.9543325526932084 1665.0 213.59078669548035 26
ECK120000092 ECB_RS03440 1.0 1191.0 130.3025290966034 27
ECK120000104 ECB_RS22920 1.0 471.0 17.52278208732605 28
ECK120000109 ECB_RS23480 1.0 477.0 17.6056706905365 29
ECK120000110 ECB_RS13105 0.9623693379790941 1413.0 173.17975497245789 30
ECK120000114 ECB_RS02710 0.9885823025689819 1041.0 95.40339803695679 31
ECK120000120 ECB_RS10265 0.9696714406065712 2334.0 326.2552881240845 32
ECK120000125 ECB_RS04065 1.0 552.0 22.796819925308228 33
ECK120000126 ECB_RS03325 1.0 591.0 26.716259002685547 34
ECK120000127 ECB_RS12970 0.9907493061979649 2148.0 296.6641249656677 35
ECK120000129 ECB_RS14195 0.9884020618556701 1539.0 197.269296169281 36
ECK120000130 ECB_RS00150 0.9675767918088737 1149.0 125.43546986579895 37
ECK120000134 ECB_RS10625 0.9612903225806452 756.0 51.23076295852661 38
ECK120000140 ECB_RS06330 0.9853694220921726 1353.0 165.32950901985168 39
ECK120000143 ECB_RS06635 0.9774859287054409 1050.0 99.24948406219482 40
ECK120000155 ECB_RS01495 1.0 1275.0 149.62861108779907 41
ECK120000161 ECB_RS05005 1.0 510.0 22.193202257156372 42
ECK120000169 ECB_RS02580 0.9982532751091703 1140.0 129.09815502166748 43
ECK120000171 ECB_RS01095 1.0 660.0 38.03315210342407 44
ECK120000173 ECB_RS01405 0.9771547248182763 948.0 83.37827777862549 45
ECK120000174 ECB_RS25315 0.987058237929318 1992.0 287.5146849155426 46
ECK120000175 ECB_RS01145 0.9839743589743589 615.0 31.69323492050171 47
ECK120000176 ECB_RS00675 0.9880952380952381 330.0 11.428565979003906 48
ECK120000183 ECB_RS11195 1.0 1374.0 173.48068594932556 49
ECK120000190 ECB_RS07960 0.94106463878327 1017.0 95.3180468082428 50
ECK120000192 ECB_RS04025 0.5017825311942959 834.0 61.469618797302246 51
ECK120000198 ECB_RS23735 0.9952550415183867 837.0 61.97277903556824 52
ECK120000205 ECB_RS13200 0.49871332990221307 1419.0 180.76415061950684 53
ECK120000207 ECB_RS24770 0.9766187050359713 1095.0 116.24529814720154 54
ECK120000208 ECB_RS00245 0.9786096256684492 921.0 76.48136234283447 55
ECK120000209 ECB_RS10280 0.9770354906054279 1890.0 262.34961318969727 56
ECK120000210 ECB_RS06525 1.0 660.0 35.6344633102417 57
ECK120000218 ECB_RS05735 1.0 369.0 12.544301748275757 58
ECK120000219 ECB_RS00725 0.9882429784454605 1518.0 197.4966630935669 59
ECK120000220 ECB_RS03110 0.5547169811320755 408.0 15.096138954162598 60
ECK120000222 ECB_RS02235 0.789272030651341 231.0 8.521353006362915 61
ECK120000223 ECB_RS07600 1.0 996.0 87.93101596832275 62
ECK120000224 ECB_RS00135 0.9956616052060737 456.0 17.165208101272583 63
ECK120000225 ECB_RS07255 1.0 1716.0 231.87099623680115 64
ECK120000228 ECB_RS03160 0.997698504027618 864.0 67.77182483673096 65
ECK120000230 ECB_RS14270 1.0 1416.0 179.83631801605225 66
ECK120000239 ECB_RS01465 1.0 1932.0 269.6579079627991 67
ECK120000241 ECB_RS04030 0.9948186528497409 381.0 13.485917091369629 68
ECK120000245 ECB_RS06595 0.9849462365591398 459.0 18.170244216918945 69
ECK120000247 ECB_RS05440 1.0 450.0 17.446388959884644 70
ECK120000250 ECB_RS05180 0.9938271604938271 642.0 34.64302396774292 71
ECK120000252 ECB_RS09125 1.0 1299.0 153.42359399795532 72
ECK120000253 ECB_RS01960 0.9685452162516383 747.0 49.656189918518066 73
ECK120000262 ECB_RS01875 0.9896103896103896 762.0 51.926676988601685 74
ECK120000265 ECB_RS08130 1.0 735.0 48.25332808494568 75
ECK120000271 ECB_RS03810 0.9752577319587629 954.0 82.1404128074646 76
ECK120000277 ECB_RS13565 0.9900793650793651 999.0 90.50689101219177 77
ECK120000279 ECB_RS12835 1.0 2148.0 312.9176309108734 78
ECK120000284 ECB_RS11700 1.0 768.0 52.57239818572998 79
ECK120000285 ECB_RS08140 1.0 522.0 21.819153785705566 80
ECK120000294 ECB_RS08730 0.968299711815562 1362.0 170.2523808479309 81
ECK120000295 ECB_RS08120 0.9990403071017274 2079.0 294.0519630908966 82
ECK120000301 ECB_RS07845 0.9644012944983819 603.0 30.418821811676025 83
ECK120000315 ECB_RS08920 0.49626467449306294 1497.0 192.99871516227722 84
ECK120000316 ECB_RS05440 0.5054773082942097 465.0 18.102400064468384 85
ECK120000317 ECB_RS14260 0.4992816091954023 1005.0 91.5124340057373 86
ECK120000318 ECB_RS06725 0.5126705653021443 414.0 15.329358100891113 87
ECK120000319 ECB_RS03920 0.981675392670157 753.0 51.01819705963135 88
ECK120000325 ECB_RS10785 0.9946018893387314 735.0 47.91080403327942 89
ECK120000328 ECB_RS09830 0.9342465753424658 702.0 40.586869955062866 90
ECK120000329 ECB_RS00345 1.0 558.0 24.760371923446655 91
ECK120000335 ECB_RS00290 0.9876543209876543 1767.0 237.18927478790283 92
ECK120000342 ECB_RS07175 0.5582386363636364 648.0 34.385359048843384 93
ECK120000346 ECB_RS25450 0.49593023255813956 1317.0 155.37632393836975 94
ECK120000349 ECB_RS05475 0.9987893462469734 1647.0 211.6052601337433 95
ECK120000350 ECB_RS14040 0.972520908004779 1647.0 211.6863980293274 96
ECK120000355 ECB_RS02560 1.0 1017.0 93.27337694168091 97
ECK120000361 ECB_RS09085 1.0 1020.0 94.90279197692871 98
ECK120000362 ECB_RS00345 0.9768881551795295 2391.0 345.7594609260559 99
ECK120000365 ECB_RS06445 0.9896678966789668 1344.0 165.30911779403687 100
ECK120000367 ECB_RS11085 0.9773627617430674 1743.0 232.85626578330994 101
ECK120000373 ECB_RS09605 0.9894523326572008 2448.0 352.79812502861023 102
ECK120000376 ECB_RS25125 0.992952783650458 1410.0 176.90259313583374 103
ECK120000378 ECB_RS13765 0.9831697054698457 1410.0 177.25864505767822 104
ECK120000380 ECB_RS12830 0.9962121212121212 1050.0 99.93791103363037 105
ECK120000387 ECB_RS11195 0.9777341191879503 1506.0 196.69157028198242 106
ECK120000393 ECB_RS09245 0.9476372924648787 758.0 51.23846507072449 107
ECK120000397 ECB_RS23850 0.9860432658757851 1419.0 182.7951159477234 108
ECK120000401 ECB_RS08535 0.9889328063241106 1254.0 151.44726991653442 109
ECK120000404 ECB_RS09035 0.4994475138121547 1407.0 171.04257702827454 110
ECK120000405 ECB_RS11890 0.9970566593083149 1353.0 161.4963550567627 111
ECK120000406 ECB_RS12910 0.970880211780278 1485.0 184.45491290092468 112
ECK120000407 ECB_RS00610 0.9956896551724138 459.0 17.459901094436646 113
ECK120000410 ECB_RS01385 1.0 258.0 8.597522735595703 114
ECK120000417 ECB_RS10635 1.0 2415.0 335.764564037323 115
ECK120000424 ECB_RS01505 0.975485188968335 963.0 83.27013492584229 116
ECK120000425 ECB_RS00700 0.9573495811119573 1281.0 151.84423303604126 117
ECK120000438 ECB_RS06910 0.9057777777777778 1068.0 104.2850239276886 118
ECK120000444 ECB_RS05235 0.9401574803149606 612.0 30.646350145339966 119
ECK120000449 ECB_RS08405 0.994991652754591 1191.0 133.1000578403473 120

ECK120000450 ECB_RS24810 0.9952267303102625 414.0 14.776495933532715 121
ECK120000453 ECB_RS15115 0.587871982032566 1395.0 171.27776098251343 122
ECK120000457 ECB_RS03620 1.0 921.0 75.66284894943237 123
ECK120000464 ECB_RS02630 1.0 588.0 28.00956916809082 124
ECK120000466 ECB_RS03325 1.0 858.0 65.11592984199524 125
ECK120000468 ECB_RS06840 0.9870967741935484 612.0 31.0077908039093 126
ECK120000471 ECB_RS08600 0.9689833429063757 1710.0 221.2636649608612 127
ECK120000474 ECB_RS04410 0.9761904761904762 411.0 14.400672912597656 128
ECK120000481 ECB_RS08615 0.9440298507462687 1038.0 94.72803783416748 129
ECK120000482 ECB_RS03950 0.9640062597809077 1251.0 138.60925793647766 130
ECK120000483 ECB_RS08535 1.0 894.0 69.19720983505249 131
ECK120000492 ECB_RS07450 0.500768049155146 492.0 19.43333625793457 132
ECK120000500 ECB_RS01980 0.9948761742100769 1164.0 126.85235095024109 133
ECK120000509 ECB_RS01970 0.9642074506939372 2685.0 366.60290789604187 134
ECK120000513 ECB_RS12575 0.9738260200153964 1278.0 143.9591829776764 135
ECK120000518 ECB_RS01280 1.0 1083.0 105.94924211502075 136
ECK120000520 ECB_RS00885 0.9974051248783652 3075.0 401.6190960407257 137
ECK120000528 ECB_RS08030 0.4966722129783694 894.0 71.40839719772339 138
ECK120000532 ECB_RS11385 0.9803395889186773 1104.0 114.92078804969788 139
ECK120000533 ECB_RS11345 0.9647266313932981 1110.0 114.83289003372192 140
ECK120000534 ECB_RS11735 0.9453717754172989 1278.0 150.07341480255127 141
ECK120000535 ECB_RS01350 0.9966144731273805 2355.0 330.08455085754395 142
ECK120000536 ECB_RS00420 1.0 1425.0 179.23214507102966 143
ECK120000537 ECB_RS02400 1.0 237.0 8.151165008544922 144
ECK120000541 ECB_RS00080 0.9880478087649402 495.0 19.08577871322632 145
ECK120000544 ECB_RS08625 0.997874601487779 936.0 79.59467697143555 146
ECK120000546 ECB_RS14195 0.9973753280839895 1518.0 191.60538387298584 147
ECK120000550 ECB_RS05590 0.9770334928229665 1029.0 95.94755220413208 148
ECK120000556 ECB_RS05600 0.9607120933087784 1593.0 207.4119791984558 149
ECK120000561 ECB_RS05700 1.0 801.0 57.09046912193298 150
ECK120000562 ECB_RS25390 0.9953379953379954 852.0 64.01255702972412 151
ECK120000566 ECB_RS01890 0.49624060150375937 834.0 61.058659076690674 152
ECK120000567 ECB_RS15200 0.9424561403508772 1380.0 169.810711145401 153
ECK120000583 ECB_RS11335 0.9893877551020408 2433.0 347.0435702800751 154
ECK120000593 ECB_RS05515 0.9933110367892977 294.0 10.195611000061035 155
ECK120000595 ECB_RS06490 1.0 927.0 77.71511769294739 156
ECK120000596 ECB_RS05655 1.0 531.0 22.494120836257935 157
ECK120000599 ECB_RS02065 0.986451276706618 1902.0 266.5388751029968 158
ECK120000601 ECB_RS10560 1.0 1044.0 99.71074032783508 159
ECK120000604 ECB_RS07335 1.0 1110.0 112.74881720542908 160
ECK120000605 ECB_RS13555 0.987027027027027 915.0 74.09168910980225 161
ECK120000608 ECB_RS11460 0.9989577905158937 1914.0 7638.287184238434 162
ECK120000610 ECB_RS10770 0.9379363847944143 1245.0 144.70342421531677 163
ECK120000620 ECB_RS09275 0.9943396226415094 1053.0 98.44130992889404 164
ECK120000621 ECB_RS10600 0.9405684754521964 747.0 49.95353102684021 165
ECK120000627 ECB_RS02090 0.961139896373057 753.0 50.425053119659424 166
ECK120000631 ECB_RS02285 0.9909694555112882 3744.0 471.0990288257599 167
ECK120000637 ECB_RS04095 1.0 681.0 38.281566858291626 168
ECK120000640 ECB_RS04810 0.9545741324921135 1545.0 200.92967772483826 169
ECK120000641 ECB_RS02695 0.999466097170315 3741.0 465.016154050827 170
ECK120000642 ECB_RS03930 0.9848369977255497 1305.0 153.69636487960815 171
ECK120000643 ECB_RS04450 1.0 432.0 16.073127269744873 172
ECK120000644 ECB_RS06990 0.9657924743443558 858.0 66.96733689308167 173

KeyboardInterrupt: